import cadquery as cq

d1 = 8.2
d2 = 7

res = (cq.Workplane("XY")
        .circle(d1/2)
        .workplane(2)
        .circle(d2/2)
        .loft()
        .faces(">Z")
        .workplane()
        .circle(d1/2)
        .workplane(2)
        .circle(d2/2)
        .loft()
        .faces(">Z")
        .workplane()
        .circle(d1/2)
        .workplane(2)
        .circle(d2/2)
        .loft()
        .faces(">Z")
        .workplane()
        .circle(d1/2)
        .workplane(2)
        .circle(d2/2)
        .loft()
        .faces(">Z")
        .workplane()
        .circle(d1/2)
        .workplane(2)
        .circle(d2/2)
        .loft()
        .faces(">Z")
        .workplane()
        .circle(d1/2)
        .workplane(1)
        .circle(d2/2)
        .loft()
        .circle(3/2)
        .cutThruAll()
        .faces(">Z")
        .workplane()
        .rect(1.5, 10)
        .cutBlind(-8)
)

show_object(res)
