width = 27
length = 70
height = 14

# shell thickness
th = 2.5
# shell fillet radius
fillet_r = 2

